/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package RestAssured

import com.jayway.restassured.response.Cookie
import org.junit.Assert
import org.junit.Test

class RestAssuredImpl: AbstractRestAssured() {
    
    @Test
    fun `Get Endpoint`() {

        val token: String = "someToken"
        val cookie: Cookie = Cookie.Builder("someCookieName", token).build()
        val params = hashMapOf<String, String>(Pair("testParam", "paramValue"))
        val baseUri = "http://localhost:8080/test-app/api/v1/get"

        //Preform your request here after declaring all parameters. 
        val response = getRequestGenerator(token, params, cookie, baseUri)

        //Neatly Print out your responses. 
        response.body.prettyPrint()

        //You can Preform many different assertion actions here. 
        Assert.assertEquals("Request returns expected 200 OK.", 200, response.statusCode)
    }

    @Test
    fun `Post Endpoint`() {

        val token: String = "someToken"
        val cookie: Cookie = Cookie.Builder("someCookieName", token).build()
        val params = hashMapOf<String, String>(Pair("testParam", "paramValue"))

        //Your body can be any type of value, object, or type, does not need to be strict JSON
        val body = "someValue"

        val baseUri = "http://localhost:8080/test-app/api/v1/post"

        //Preform your request here after declaring all parameters. 
        val response = getRequestGenerator(token, params, cookie, baseUri, body)

        //Neatly Print out your responses. 
        response.body.prettyPrint()

        //You can Preform many different assertion actions here. 
        Assert.assertEquals("Request returns expected 201 OK.", 201, response.statusCode)
    }

    @Test
    fun `Put Endpoint`() {

        val token: String = "someToken"
        val cookie: Cookie = Cookie.Builder("someCookieName", token).build()
        val params = hashMapOf<String, String>(Pair("testParam", "paramValue"))

        //Your body can be any type of value, object, or type, does not need to be strict JSON
        val body = "someValue"

        val baseUri = "http://localhost:8080/test-app/api/v1/put"

        //Preform your request here after declaring all parameters. 
        val response = putRequestGenerator(token, params, cookie, baseUri, body)

        //Neatly Print out your responses. 
        response.body.prettyPrint()

        //You can Preform many different assertion actions here. 
        Assert.assertEquals("Request returns expected 201 OK.", 201, response.statusCode)
    }

}
